name: sarand-2.0.1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bzip2
  - gzip
  - bandage=0.9.0
  - blast=2.17.0
  - cd-hit=4.8.1
  - minimap2=2.31
  - gfapy=1.2.3
  - networkx
  - biopython
  - pyrodigal
  - python
  - zlib
  - zlib-ng
  - zstd
  - pip 
