name: test_package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: "Install Conda environment with Micromamba"
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: conda_env.yaml
          environment-name: sarand
          cache-env: true
      - name: "Install sarand"
        shell: bash -l {0}
        run: pip install '.[test]'
      - name: "Run test"
        shell: bash -l {0}
        run: bash test/test.sh
